# Dependencies


# Permalinks
permalink:        pretty

# Setup
title:            "ASG Blog"
description:      "AverageSecurityGuy"
url:              "https://averagesecurityguy.github.io"
baseurl:          "/"

author:
  name:           "Stephen Haywood"
  url:            "https://twitter.com/averagesecguy"

paginate:         5
