# Dependencies


# Permalinks
permalink:        pretty

# Setup
title:            "ASG Blog"
description:      "AverageSecurityGuy"

author:
  name:           "Stephen Haywood"
  url:            "https://twitter.com/averagesecguy"

paginate:         5
